# Generated by Django 5.2.17 on 2026-09-29 11:27

import medfind_project.session_auth
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
            bases=(medfind_project.session_auth.PasswordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('pharmacy', 'Pharmacy'), ('admin', 'Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(max_length=100)),
                ('actor_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
