# Generated by Django 5.2.17 on 2026-09-29 11:27

import django.core.validators
import django.db.models.deletion
import medfind_project.session_auth
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'pharmacies',
                'ordering': ['business_name'],
            },
            bases=(medfind_project.session_auth.PasswordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PharmacyVerification',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='pharmacy_app.pharmacy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to='admin_app.admin')),
            ],
            options={
                'ordering': ['-verification_id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock')], default='available', max_length=20)),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='home_app.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pharmacy_app.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'inventory',
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'medicine'), name='unique_medicine_per_pharmacy')],
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='pharmacy_app.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'operating hours',
                'ordering': ['pharmacy', 'days_of_week'],
                'constraints': [models.UniqueConstraint(fields=('pharmacy', 'days_of_week'), name='unique_day_per_pharmacy')],
            },
        ),
    ]
